services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: kutubuku_app
        restart: unless-stopped
        volumes:
            - .:/var/www
        depends_on:
            - mysql

    nginx:
        image: nginx:alpine
        container_name: kutubuku_nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        container_name: kutubuku_mysql
        restart: always
        environment:
            MYSQL_DATABASE: kutubuku_db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: root
        ports:
            - "3307:3306"
        volumes:
            - dbdata:/var/lib/mysql
            - ./docker/mysql:/docker-entrypoint-initdb.d

volumes:
    dbdata:
